apiVersion: v1
kind: Service
metadata:
  name: image-processing
  
spec:
  type: ClusterIP
  ports:
    - targetPort: 80
      port: 80
      ClusterIP: 8080
  selector:
      app: myapp
      type: front-end
