apiVersion: v1
kind: service
metadata:
  name: myapp-services
  
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
  selectior:
      app: myapp
      type: front-end
